### ISSUE TITLE
First page after teacher login

### ISSUE THREAD

**Issue by qarnac** [qarnac/CyberScavenger#7]
Currently, the page is blank after a teacher logs in. It would be nice to present some information such as some welcome or tutorial information for first time teachers. Once a teacher has created one or more hunts, it would be nice to pull the latest hunt.

**Comment by phantosmia** [comment]
Already added the last hunt to be loaded if the teacher has already created a hunt. I'm working in a image-tutorial to add if the teacher hasn't added a new hunt yet.
